### ISSUE TITLE
WP-4372 CP-2234 Add .poll() to BaseRequest to support configurable polling

### ISSUE THREAD

**Issue by nickmiller-wf** [Workiva/w_transport#183] opened 2016-07-20 21:59 UTC
We have a situation where we'd like to do some auto retries on a request that returns a [202 Accepted](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success), but after some digging, it appears that retires are only considered when a RequestException has been thrown, which excludes any response code in the 2xx range

See https://github.com/Workiva/w_transport/blob/master/lib/src/http/common/request.dart#L629

Is there any particular reason for this restriction?

**Comment by rm-astro-wf** [comment] 2016-07-20 21:59
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/183/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by maxwellpeterson-wf** [comment] 2016-07-20 22:11
The goal of auto-retrying is to prevent consumers from having to do error handling for transient errors, such as a temporarily downed wifi connection or a 503 while a server is coming up.

What you describe could instead leverage a polling approach like so:

```dart
Future _poll() async {
  Response response = await Http.get(uri);
  if (response.status == 202) return _poll();
  return response;
}
```

I could see a case being made to allow this to kind of behavior in the auto-retry functionality by adding `202` to the `autoRetry.forStatusCodes` list. But I'll defer to @evanweible-wf for his opinion on that.

**Comment by evanweible-wf** [comment] 2016-07-25 06:10
@nickmiller-wf I talked this over with Max and I think we've decided that this should be addressed in a slightly different way. Like Max mentioned, this is really more about polling an endpoint until the expected response is returned. The autoRetry functionality was designed specifically to handle request failures, and at this point I'm standing by the decision to interpret any 2xx status as a success. Additionally, I'd like to avoid expanding the API to allow modification of that success criteria, as it seems more like a hack to leverage the auto retry logic.

That being said, the auto retry logic with fixed/exponential backoff is certainly useful and could be applied outside the context of handling request failures.

We can add a `.poll()` method to the `BaseRequest` class that would be used in place of `.get()` or `.send()`. This method would expect a function that will be called with a response each time a polling request is made to determine whether or not polling is complete. The `Future` returned from a call to `.poll()` will only complete when said function returns `true` and would resolve with the final response. For example:

```dart
var request = new JsonRequest()
  ..uri = Uri.parse('/status/');

var backOff = new BackOff.fixed(new Duration(seconds: 5));
var response = await request.poll('GET', backOff: backOff, doneWhen: (response) {
    return response.status == 200;
  });
```

Internally, we can leverage the `.clone()` method to make this happen. That way you can configure the request as necessary (even including enabling autoRetry for transient failures) before starting the polling, and each polling request will inherit the exact same configuration.

What are your thoughts on that approach? Would that be an acceptable solution for your use case?

**Comment by nickmiller-wf** [comment] 2016-07-25 14:32
@evanweible-wf Thanks for the writeup - I like that approach and I think it would work just fine in our use case. My only suggestion from here would be to make the rationalization behind autoRetry more explicit in the docs here: https://github.com/Workiva/w_transport#automatic-request-retrying - To me, the docs imply I should be able to pass any status code and get retry behavior on it. Other than that, everything's good on my end 👍

**Comment by evanweible-wf** [comment] 2016-07-25 14:35
Definitely agree, I'll clarify the docs!

**Comment by evanweible-wf** [comment] 2016-07-25 14:41
https://github.com/Workiva/w_transport/issues/199

**Closed** 2017-12-06 18:28 UTC
Labels: area-http, type: Feature
