### ISSUE TITLE
Investigate differences in unit test coverage amounts

### ISSUE THREAD

**Issue by jayudey-wf** [Workiva/w_transport#21] opened 2015-06-10 21:38 UTC
There are times that the coverage report generated is different between what is out on codecov.io versus locally.

The differences always seem to manifest themselves in w_http_client.dart.

codecov - http://screencast.com/t/0mM6aCqAW
locally - http://screencast.com/t/DkfxBklGIr

**Comment by evanweible-wf** [comment] 2015-06-16 21:25
I think this may be related to an issue I discovered in the way browser tests are run in the dart_codecov_generator tool. Possible fix here: https://github.com/ekweible/dart_codecov_generator/tree/fix-browser-tests

**Comment by evanweible-wf** [comment] 2015-08-21 02:25
This should be fixed in #53

**Comment by evanweible-wf** [comment] 2015-09-01 14:23
Unable to reproduce after #53, I believe this is fixed now.

**Closed by evanweible-wf** 2015-09-01 14:23 UTC
